ES/ES/Controllers/MyController.cs
using ES.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ES.Controllers
{
    public class MyController : BaseController
    {
       
        [HttpGet]
        public ActionResult Login()
        {
            ViewBag.Title = "Giriş Yap";
            return View();
        }
        [HttpPost]
        public ActionResult Login(Customer customer)
        {
            if(ModelState.IsValid)
            {
                var cus = Db.Customers.SingleOrDefault(d => d.EmailAdress.Equals(customer.EmailAdress) && 
                    d.Password.Equals(customer.Password));
                if (cus != null)
                {
                    Session["LoginKey"] = cus;
                    return RedirectToAction("Index", "Home");
                }

            }
            ViewBag.Title = "Grirş Yap";
            return View(customer);

        }
        public ActionResult Index()
        {
            ViewBag.Title = "Sepetim";
            ViewBag.BasketProducts = Db.CustomerOfBaskets.Where(d => d.CustomerId == CurrentCustomer.Id).Select(d => d.Product).ToList();

            ViewBag.Sales = Db.Sales.Where(d => d.CustomerId == CurrentCustomer.Id).ToList();
            return View();
        }
        public ActionResult AddBasket(int? id)
        {
            if (id.HasValue)
            {
                //var customer = (Session["LoginKey"] as Customer);
                if (!Db.CustomerOfBaskets.Any(d => d.ProductId == id && d.CustomerId ==CurrentCustomer.Id))
                {
                     var basketItem = new CustomerOfBasket
                {
                    CustomerId = CurrentCustomer.Id,
                    ProductId = id.Value
                };
                Db.CustomerOfBaskets.InsertOnSubmit(basketItem);
                Db.SubmitChanges();
                }
               
              
            }
            Session["LoginKey"] = Db.Customers.Single(d => d.Id == CurrentCustomer.Id);
            return RedirectToAction("Index");


        }
        public ActionResult RemoveBasket(int? id)
        {
            if (id.HasValue)
            {
                //var customer = (Session["LoginKey"] as Customer);
                var basketItem = Db.CustomerOfBaskets.SingleOrDefault(d =>d.ProductId == id && d.CustomerId == CurrentCustomer.Id);
                if (basketItem != null)
                {
                    Db.CustomerOfBaskets.DeleteOnSubmit(basketItem);
                    Db.SubmitChanges(); 
                }
              

            }
            Session["LoginKey"] = Db.Customers.Single(d => d.Id == CurrentCustomer.Id);
            return RedirectToAction("Index");


        }
    }
}

ES/ES/Controllers/ProductController.cs
using ePayment;
using ES.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ES.Controllers
{
    public class ProductController : BaseController
    {
        //
        // GET: /Product/
        //Urun listesi , Kategoriye gore  sıralama
        public ActionResult Index(string id,DefaultFilter filter)
        {
            ViewBag.Title = "Ürün Listesi";
            var list = Db.Products.AsQueryable();
            if(!string.IsNullOrEmpty(id))
            {
                list = list.Where(d => d.Category.SeoText.Equals(id));
                ViewBag.CategoryName = Db.Categories.Single(d => d.SeoText.Equals(id)).Text;
            }
            list = AddFilter(filter, list);
            return View(list.ToList());
        }
        //private IQueryable<Models.Product> AddFilter(DefaultFilter filter, IQueryable<Models.Product> list)
        //{
        //    throw new NotImplementedException();
        //}
       
        public    ActionResult Detail(string id)
        {
            
            var product = Db.Products.SingleOrDefault(d => d.Seo.Equals(id));
            if (product == null)
                throw new Exception("Urun bulunamadı");
            ViewBag.Title = product.Title;
            return View(product);
        }
        public ActionResult Sale(int id)
        {
            var product = Db.Products.SingleOrDefault(d => d.Id.Equals(id));
            if (product == null)
                return RedirectToAction("Index");
            return View(product);

        }

        [HttpPost]
        public ActionResult Sale(UserCardInfo cardInfo)
        {
            var product = Db.Products.SingleOrDefault(d => d.Id == cardInfo.Id);
            if (product == null)
            return RedirectToAction("Index");
            ViewBag.Result = "";
            var payment = new cc5payment
            {
                host = "host",
                name = "",
                password = "",
                clientid = "",
                orderresult = 0,
                cardnumber = cardInfo.CardNumber,
                expmonth = cardInfo.ExpMonth.ToString(),
                expyear = cardInfo.ExpYear.ToString(),
                cv2 = cardInfo.SecurityNumber,
                currency = "949",
                chargetype = "Auth",
                ip = Request.ServerVariables["REMOTE_ADDR"],
                subtotal = product.Price.ToString(),
                taksit = "1"
            };
            string bankaSonuc = payment.processorder(); //Methot Çagır
            string bankaHata = payment.errmsg; //Dönen hatamesajı
            string bakaOid = payment.oid;//Dönen order id
            string bankaAppr = payment.appr; //Dönen işlem sonucu
            string bankaProv = payment.code; //Dönen provizyon numarası

            if (bankaSonuc == "1")
            {
                if (bankaAppr == "Approved") //Ödemeişlemi tamam
                {
                    ViewBag.Result = "BanKa ödemeyi kabul etti.Ödeme işlemi başarıile tamamlandı";

                }
                else if (bankaAppr == "Declined") //Ödeme işlemi reddedildi
                {
                    ViewBag.Result = "Banka ödemeyi reddetti";
                }
                else
                {
                    ViewBag.Result = "Banka ile işlem kurulmadı";
                }
            }
            var sale = new Sale
            {
                CargoPrice = 20,
                CustomerId = CurrentCustomer.Id,
                ProductId = cardInfo.Id,
                RecordDate= DateTime.Now,
                SaleState = (short)SaleState.PendingCheck
            };
            Db.Sales.InsertOnSubmit(sale);
            Db.SubmitChanges();
               return RedirectToAction("Index");
         
        }

    }
  
}

ES/ES/Views/Product/Detail.cshtml
@model ES.Models.Product

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div>
@{Html.RenderPartial("ProductDetail", Model);
   
}
</div>


@*<div class="categories">
    <ul>
        @foreach (var item in ViewBag.categoryList)
        {
            <li><a href="@Url.Action("List","Product",new {id=item.SeoText})" class="active"><span>@item.Text</span></a></li>
        }

    </ul>
</div>*@
         @*<div class="detail">
             <div class="image">
                 <a href="#"><img src="@Model.ImageUrl" style="width:300px !important;" alt="@Model.Title" /></a>
             </div>
             <p>
                 Urun No: <span>@Model.Id</span><br />
                 Boyut listesi : <span>@Model.Attributes</span><br />
                 Marka Adı: <a href="#">@Model.Model</a>
             </p>
             <p class="price">     Urun Fiyatı <strong>@Model.Price</strong></p>     
         </div>*@                                 
                                           

ES/ES/Views/Product/Index.cshtml
@using ES.Models
@model IList<ES.Models.Product>
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
<h2 style="height:50px;border-bottom:1px solid #f3f3f3;">
    Ürün Listesi @(string.IsNullOrEmpty(ViewBag.CategoryName) ? "" : " | " + ViewBag.CategoryName)</h2>
<ul>
    <li class="orderlinks">
        @UrlCreater.Create(ProductColumnEnum.Price,Request.Params)
    </li>
    <li>
        @UrlCreater.Create(ProductColumnEnum.Model, Request.Params)
    </li>
    <li>
        @UrlCreater.Create(ProductColumnEnum.Title, Request.Params)
    </li>
</ul>
<div class="tab-content" >

    <div class="items" style="width: 750px !important;">
        <div class="cl">&nbsp;</div>
        <ul>
            @foreach (var item in Model)
            {
                <li>
                    @{Html.RenderPartial("SimpleProduct", item);}
                    <p>
                        <a href="@Url.Action("AddBasket", "My", new { id = item.Id })">Sepete ekle</a>
                        <a href="@Url.Action("Sale", "Product", new {id = item.Id })">Satın Al</a>
                    </p>
                </li>
            }

        </ul>
        <div class="cl">&nbsp;</div>
    </div>
</div>

ES/ES/Views/Product/Sale.cshtml
@model ES.Models.Product

@{
    ViewBag.Title = "Sale";
}

@{Html.RenderPartial("ProductDetail", Model);}
@using (Html.BeginForm())
{
    var yearList = new List<int>();
    
    var monthList = new List<int>();
    
    for (var i = 12; i < 30; i++){ yearList.Add(i);}
    
    for (var i = 1; i <= 12; i++) { monthList.Add(i);}
    
    @Html.HiddenFor(d => d.Id)
    @Html.Label("Kart Numarası")
    @Html.TextBox("CardNumber")
    @Html.Label("CV2Numarası")
    @Html.TextBox("SecurityNumber")
    @Html.Label("Kart isim soyisim")
    @Html.TextBox("CardHasName")
    @Html.Label("Son kullanma Yılı")
    @Html.DropDownList("ExpYear", new SelectList(yearList))
    @Html.Label("Son Kullanma Ayı")
    @Html.DropDownList("ExpMonth" , new SelectList(monthList))
    <input type="submit" value="Satısı tamamla" />
}